### ISSUE TITLE
Invariant Violation: Element type is invalid:expected a string (for built-in components)or a class/function (for composite components) but got......Check the render method of 'App'.

### ISSUE THREAD

**Issue by shravanteegala** [vikrantnegi/react-native-searchable-flatlist#1]
![simulator screen shot - iphone x - 2019-02-19 at 17 14 14](https://user-images.githubusercontent.com/13646977/53013005-9b686a80-346a-11e9-820a-613cd8ef6c54.png)

**Comment by shravanteegala** [comment]
I Find the error in <List...../>  in render method.

**Comment by vikrantnegi** [comment]
Hey, @shravanteegala thanks for pointing that out.

I've updated the react native as well as other dependencies. Can you check the updated version?

**Comment by shravanteegala** [comment]
ok

**Comment by vikrantnegi** [comment]
updated the project
