### ISSUE TITLE
Not finding the package in the yarn repository?

### ISSUE THREAD

**Issue by benwilburn** [vikrantnegi/react-native-searchable-flatlist#2]
I'm trying to install the package to my project but getting 'error An unexpected error occurred: "http://registry.npmjs.org/react-native-searchable-flatlist: Not found".'

**Comment by vikrantnegi** [comment]
Hi @benwilburn 
This is not a .npm package that can be installed from there. But you can use its source code for reference and use it according to your need. Let me know if you need any help.

**Comment by divs246** [comment]
if i am searching in the search bar its not entering to search and static data is displaying.

**Comment by vikrantnegi** [comment]
Did you clone it or you are using it in your app?

 I'm able to search properly after cloning.
